COUNTRIES = [
    # Top regional & common countries
    {"code": "RS", "name": "Srbija", "name_en": "Serbia"},
    {"code": "BA", "name": "Bosna i Hercegovina", "name_en": "Bosnia and Herzegovina"},
    {"code": "ME", "name": "Crna Gora", "name_en": "Montenegro"},
    {"code": "HR", "name": "Hrvatska", "name_en": "Croatia"},
    {"code": "MK", "name": "Severna Makedonija", "name_en": "North Macedonia"},
    {"code": "SI", "name": "Slovenija", "name_en": "Slovenia"},
    {"code": "DE", "name": "Nemačka", "name_en": "Germany"},
    {"code": "AT", "name": "Austrija", "name_en": "Austria"},
    {"code": "CH", "name": "Švajcarska", "name_en": "Switzerland"},
    {"code": "IT", "name": "Italija", "name_en": "Italy"},
    {"code": "HU", "name": "Mađarska", "name_en": "Hungary"},
    {"code": "RO", "name": "Rumunija", "name_en": "Romania"},
    {"code": "BG", "name": "Bugarska", "name_en": "Bulgaria"},
    {"code": "GR", "name": "Grčka", "name_en": "Greece"},
    {"code": "TR", "name": "Turska", "name_en": "Turkey"},
    {"code": "RU", "name": "Rusija", "name_en": "Russia"},
    {"code": "UK", "name": "Velika Britanija", "name_en": "United Kingdom"},
    {"code": "US", "name": "SAD", "name_en": "USA"},
    {"code": "CN", "name": "Kina", "name_en": "China"},

    # Rest of the world (Alphabetical by Serbian name)
    {"code": "AL", "name": "Albanija", "name_en": "Albania"},
    {"code": "DZ", "name": "Alžir", "name_en": "Algeria"},
    {"code": "AD", "name": "Andora", "name_en": "Andorra"},
    {"code": "AO", "name": "Angola", "name_en": "Angola"},
    {"code": "AG", "name": "Antigva i Barbuda", "name_en": "Antigua and Barbuda"},
    {"code": "AR", "name": "Argentina", "name_en": "Argentina"},
    {"code": "AU", "name": "Australija", "name_en": "Australia"},
    {"code": "AF", "name": "Avganistan", "name_en": "Afghanistan"},
    {"code": "AZ", "name": "Azerbejdžan", "name_en": "Azerbaijan"},
    {"code": "BS", "name": "Bahami", "name_en": "Bahamas"},
    {"code": "BH", "name": "Bahrein", "name_en": "Bahrain"},
    {"code": "BD", "name": "Bangladeš", "name_en": "Bangladesh"},
    {"code": "BB", "name": "Barbados", "name_en": "Barbados"},
    {"code": "BE", "name": "Belgija", "name_en": "Belgium"},
    {"code": "BZ", "name": "Belize", "name_en": "Belize"},
    {"code": "BY", "name": "Belorusija", "name_en": "Belarus"},
    {"code": "BJ", "name": "Benin", "name_en": "Benin"},
    {"code": "BO", "name": "Bolivija", "name_en": "Bolivia"},
    {"code": "BW", "name": "Bocvana", "name_en": "Botswana"},
    {"code": "BR", "name": "Brazil", "name_en": "Brazil"},
    {"code": "BN", "name": "Brunej", "name_en": "Brunei"},
    {"code": "BF", "name": "Burkina Faso", "name_en": "Burkina Faso"},
    {"code": "BI", "name": "Burundi", "name_en": "Burundi"},
    {"code": "BT", "name": "Butan", "name_en": "Bhutan"},
    {"code": "CF", "name": "Centralnoafrička Republika", "name_en": "Central African Republic"},
    {"code": "DK", "name": "Danska", "name_en": "Denmark"},
    {"code": "DM", "name": "Dominika", "name_en": "Dominica"},
    {"code": "DO", "name": "Dominikanska Republika", "name_en": "Dominican Republic"},
    {"code": "DJ", "name": "Džibuti", "name_en": "Djibouti"},
    {"code": "EG", "name": "Egipat", "name_en": "Egypt"},
    {"code": "EC", "name": "Ekvador", "name_en": "Ecuador"},
    {"code": "GQ", "name": "Ekvatorijalna Gvineja", "name_en": "Equatorial Guinea"},
    {"code": "SV", "name": "El Salvador", "name_en": "El Salvador"},
    {"code": "ER", "name": "Eritreja", "name_en": "Eritrea"},
    {"code": "EE", "name": "Estonija", "name_en": "Estonia"},
    {"code": "SZ", "name": "Esvatini", "name_en": "Eswatini"},
    {"code": "ET", "name": "Etiopija", "name_en": "Ethiopia"},
    {"code": "FJ", "name": "Fidži", "name_en": "Fiji"},
    {"code": "PH", "name": "Filipini", "name_en": "Philippines"},
    {"code": "FI", "name": "Finska", "name_en": "Finland"},
    {"code": "FR", "name": "Francuska", "name_en": "France"},
    {"code": "GA", "name": "Gabon", "name_en": "Gabon"},
    {"code": "GM", "name": "Gambija", "name_en": "Gambia"},
    {"code": "GH", "name": "Gana", "name_en": "Ghana"},
    {"code": "GD", "name": "Grenada", "name_en": "Grenada"},
    {"code": "GE", "name": "Gruzija", "name_en": "Georgia"},
    {"code": "GY", "name": "Gvajana", "name_en": "Guyana"},
    {"code": "GT", "name": "Gvatemala", "name_en": "Guatemala"},
    {"code": "GN", "name": "Gvineja", "name_en": "Guinea"},
    {"code": "GW", "name": "Gvineja-Bisao", "name_en": "Guinea-Bissau"},
    {"code": "HT", "name": "Haiti", "name_en": "Haiti"},
    {"code": "NL", "name": "Holandija", "name_en": "Netherlands"},
    {"code": "HN", "name": "Honduras", "name_en": "Honduras"},
    {"code": "HK", "name": "Hong Kong", "name_en": "Hong Kong"},
    {"code": "IN", "name": "Indija", "name_en": "India"},
    {"code": "ID", "name": "Indonezija", "name_en": "Indonesia"},
    {"code": "IQ", "name": "Irak", "name_en": "Iraq"},
    {"code": "IR", "name": "Iran", "name_en": "Iran"},
    {"code": "IE", "name": "Irska", "name_en": "Ireland"},
    {"code": "IS", "name": "Island", "name_en": "Iceland"},
    {"code": "TL", "name": "Istočni Timor", "name_en": "East Timor"},
    {"code": "IL", "name": "Izrael", "name_en": "Israel"},
    {"code": "JM", "name": "Jamajka", "name_en": "Jamaica"},
    {"code": "JP", "name": "Japan", "name_en": "Japan"},
    {"code": "YE", "name": "Jemen", "name_en": "Yemen"},
    {"code": "AM", "name": "Jermenija", "name_en": "Armenia"},
    {"code": "JO", "name": "Jordan", "name_en": "Jordan"},
    {"code": "ZA", "name": "Južnoafrička Republika", "name_en": "South Africa"},
    {"code": "KR", "name": "Južna Koreja", "name_en": "South Korea"},
    {"code": "SS", "name": "Južni Sudan", "name_en": "South Sudan"},
    {"code": "KH", "name": "Kambodža", "name_en": "Cambodia"},
    {"code": "CM", "name": "Kamerun", "name_en": "Cameroon"},
    {"code": "CA", "name": "Kanada", "name_en": "Canada"},
    {"code": "QA", "name": "Katar", "name_en": "Qatar"},
    {"code": "KZ", "name": "Kazahstan", "name_en": "Kazakhstan"},
    {"code": "KE", "name": "Kenija", "name_en": "Kenya"},
    {"code": "CN", "name": "Kina", "name_en": "China"},
    {"code": "CY", "name": "Kipar", "name_en": "Cyprus"},
    {"code": "KG", "name": "Kirgistan", "name_en": "Kyrgyzstan"},
    {"code": "KI", "name": "Kiribati", "name_en": "Kiribati"},
    {"code": "CO", "name": "Kolumbija", "name_en": "Colombia"},
    {"code": "KM", "name": "Komori", "name_en": "Comoros"},
    {"code": "CG", "name": "Kongo (Brazavil)", "name_en": "Congo (Brazzaville)"},
    {"code": "CD", "name": "Kongo (Kinšasa)", "name_en": "Congo (Kinshasa)"},
    {"code": "CR", "name": "Kostarika", "name_en": "Costa Rica"},
    {"code": "CU", "name": "Kuba", "name_en": "Cuba"},
    {"code": "KW", "name": "Kuvajt", "name_en": "Kuwait"},
    {"code": "LA", "name": "Laos", "name_en": "Laos"},
    {"code": "LS", "name": "Lesoto", "name_en": "Lesotho"},
    {"code": "LV", "name": "Letonija", "name_en": "Latvia"},
    {"code": "LB", "name": "Liban", "name_en": "Lebanon"},
    {"code": "LR", "name": "Liberija", "name_en": "Liberia"},
    {"code": "LY", "name": "Libija", "name_en": "Libya"},
    {"code": "LI", "name": "Lihtenštajn", "name_en": "Liechtenstein"},
    {"code": "LT", "name": "Litvanija", "name_en": "Lithuania"},
    {"code": "LU", "name": "Luksemburg", "name_en": "Luxembourg"},
    {"code": "MG", "name": "Madagaskar", "name_en": "Madagascar"},
    {"code": "MW", "name": "Malavi", "name_en": "Malawi"},
    {"code": "MV", "name": "Maldivi", "name_en": "Maldives"},
    {"code": "MY", "name": "Malezija", "name_en": "Malaysia"},
    {"code": "ML", "name": "Mali", "name_en": "Mali"},
    {"code": "MT", "name": "Malta", "name_en": "Malta"},
    {"code": "MA", "name": "Maroko", "name_en": "Morocco"},
    {"code": "MH", "name": "Maršalska Ostrva", "name_en": "Marshall Islands"},
    {"code": "MU", "name": "Mauricijus", "name_en": "Mauritius"},
    {"code": "MR", "name": "Mauritanija", "name_en": "Mauritania"},
    {"code": "MX", "name": "Meksiko", "name_en": "Mexico"},
    {"code": "FM", "name": "Mikronezija", "name_en": "Micronesia"},
    {"code": "MM", "name": "Mjanmar", "name_en": "Myanmar"},
    {"code": "MD", "name": "Moldavija", "name_en": "Moldova"},
    {"code": "MC", "name": "Monako", "name_en": "Monaco"},
    {"code": "MN", "name": "Mongolija", "name_en": "Mongolia"},
    {"code": "MZ", "name": "Mozambik", "name_en": "Mozambique"},
    {"code": "NA", "name": "Namibija", "name_en": "Namibia"},
    {"code": "NR", "name": "Nauru", "name_en": "Nauru"},
    {"code": "NP", "name": "Nepal", "name_en": "Nepal"},
    {"code": "NE", "name": "Niger", "name_en": "Niger"},
    {"code": "NG", "name": "Nigerija", "name_en": "Nigeria"},
    {"code": "NI", "name": "Nikaragva", "name_en": "Nicaragua"},
    {"code": "NO", "name": "Norveška", "name_en": "Norway"},
    {"code": "NZ", "name": "Novi Zeland", "name_en": "New Zealand"},
    {"code": "CI", "name": "Obala Slonovače", "name_en": "Ivory Coast"},
    {"code": "OM", "name": "Oman", "name_en": "Oman"},
    {"code": "PK", "name": "Pakistan", "name_en": "Pakistan"},
    {"code": "PW", "name": "Palau", "name_en": "Palau"},
    {"code": "PA", "name": "Panama", "name_en": "Panama"},
    {"code": "PG", "name": "Papua Nova Gvineja", "name_en": "Papua New Guinea"},
    {"code": "PY", "name": "Paragvaj", "name_en": "Paraguay"},
    {"code": "PE", "name": "Peru", "name_en": "Peru"},
    {"code": "PL", "name": "Poljska", "name_en": "Poland"},
    {"code": "PT", "name": "Portugalija", "name_en": "Portugal"},
    {"code": "RW", "name": "Ruanda", "name_en": "Rwanda"},
    {"code": "WS", "name": "Samoa", "name_en": "Samoa"},
    {"code": "SM", "name": "San Marino", "name_en": "San Marino"},
    {"code": "ST", "name": "Sao Tome i Principe", "name_en": "Sao Tome and Principe"},
    {"code": "SA", "name": "Saudijska Arabija", "name_en": "Saudi Arabia"},
    {"code": "SC", "name": "Sejšeli", "name_en": "Seychelles"},
    {"code": "SN", "name": "Senegal", "name_en": "Senegal"},
    {"code": "KN", "name": "Sent Kits i Nevis", "name_en": "Saint Kitts and Nevis"},
    {"code": "LC", "name": "Sveta Lucija", "name_en": "Saint Lucia"},
    {"code": "VC", "name": "Sent Vinsent i Grenadini", "name_en": "Saint Vincent and the Grenadines"},
    {"code": "KP", "name": "Severna Koreja", "name_en": "North Korea"},
    {"code": "SL", "name": "Sijera Leone", "name_en": "Sierra Leone"},
    {"code": "SG", "name": "Singapur", "name_en": "Singapore"},
    {"code": "SY", "name": "Sirija", "name_en": "Syria"},
    {"code": "SK", "name": "Slovačka", "name_en": "Slovakia"},
    {"code": "SB", "name": "Solomonska Ostrva", "name_en": "Solomon Islands"},
    {"code": "SO", "name": "Somalija", "name_en": "Somalia"},
    {"code": "SD", "name": "Sudan", "name_en": "Sudan"},
    {"code": "SR", "name": "Surinam", "name_en": "Suriname"},
    {"code": "ES", "name": "Španija", "name_en": "Spain"},
    {"code": "LK", "name": "Šri Lanka", "name_en": "Sri Lanka"},
    {"code": "SE", "name": "Švedska", "name_en": "Sweden"},
    {"code": "TJ", "name": "Tadžikistan", "name_en": "Tajikistan"},
    {"code": "TH", "name": "Tajland", "name_en": "Thailand"},
    {"code": "TW", "name": "Tajvan", "name_en": "Taiwan"},
    {"code": "TZ", "name": "Tanzanija", "name_en": "Tanzania"},
    {"code": "TG", "name": "Togo", "name_en": "Togo"},
    {"code": "TO", "name": "Tonga", "name_en": "Tonga"},
    {"code": "TT", "name": "Trinidad i Tobago", "name_en": "Trinidad and Tobago"},
    {"code": "TN", "name": "Tunis", "name_en": "Tunisia"},
    {"code": "TM", "name": "Turkmenistan", "name_en": "Turkmenistan"},
    {"code": "TV", "name": "Tuvalu", "name_en": "Tuvalu"},
    {"code": "UG", "name": "Uganda", "name_en": "Uganda"},
    {"code": "AE", "name": "Ujedinjeni Arapski Emirati", "name_en": "United Arab Emirates"},
    {"code": "UA", "name": "Ukrajina", "name_en": "Ukraine"},
    {"code": "UY", "name": "Urugvaj", "name_en": "Uruguay"},
    {"code": "UZ", "name": "Uzbekistan", "name_en": "Uzbekistan"},
    {"code": "VU", "name": "Vanuatu", "name_en": "Vanuatu"},
    {"code": "VA", "name": "Vatikan", "name_en": "Vatican"},
    {"code": "VE", "name": "Venecuela", "name_en": "Venezuela"},
    {"code": "VN", "name": "Vijetnam", "name_en": "Vietnam"},
    {"code": "ZM", "name": "Zambija", "name_en": "Zambia"},
    {"code": "CV", "name": "Zelenortska Ostrva", "name_en": "Cape Verde"},
    {"code": "ZW", "name": "Zimbabve", "name_en": "Zimbabwe"},
    {"code": "TD", "name": "Čad", "name_en": "Chad"},
    {"code": "CZ", "name": "Češka", "name_en": "Czech Republic"},
    {"code": "CL", "name": "Čile", "name_en": "Chile"},
    
    # Other / Not listed
    {"code": "OTHER", "name": "Ostalo", "name_en": "Other"}
]

def get_country_list():
    return COUNTRIES

def get_country_name(code):
    for country in COUNTRIES:
        if country["code"] == code:
            return country["name"]
    return code
